# Generated by Django 4.0.5 on 2022-06-26 16:12

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ttt_game',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('startedOn', models.DateTimeField(default=datetime.datetime.now)),
                ('endedOn', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ttt_move',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('moveX', models.SmallIntegerField(default=-1)),
                ('moveY', models.SmallIntegerField(default=-1, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(2)])),
                ('movedOn', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='ttt_users',
            fields=[
                ('id', models.IntegerField(default=0, primary_key='id', serialize=False, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('registeredOn', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddIndex(
            model_name='ttt_users',
            index=models.Index(fields=['username'], name='tictactoe_t_usernam_272fcb_idx'),
        ),
        migrations.AddField(
            model_name='ttt_move',
            name='gameId',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='tictactoe.ttt_game'),
        ),
        migrations.AddField(
            model_name='ttt_move',
            name='userId',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='tictactoe.ttt_users'),
        ),
        migrations.AddField(
            model_name='ttt_game',
            name='winnerUserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tictactoe.ttt_users'),
        ),
        migrations.AddIndex(
            model_name='ttt_move',
            index=models.Index(fields=['gameId'], name='tictactoe_t_gameId__d2db5e_idx'),
        ),
        migrations.AddIndex(
            model_name='ttt_move',
            index=models.Index(fields=['userId'], name='tictactoe_t_userId__1b2e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='ttt_game',
            index=models.Index(fields=['winnerUserId'], name='tictactoe_t_winnerU_cb7b8c_idx'),
        ),
    ]
